### ISSUE TITLE
友情链接 | Chen's Blog

### ISSUE THREAD

**Issue by 0x0cqq** [ChenQiqian/comments#25]
http://blog.chenqiqian.com/links/ 

 Stay simple. Stay naïve. 恭喜你！发现了一个蒟蒻的Blog。 某高中开始学OI的蒟蒻。现高一。 不定期更新。 (≧▽≦)/

**Comment by memset0** [comment]
蒟蒻请求加友链

 * 名称：memset0的博客
 * 地址：https://memset0.scris.top
 * 简介：写点什么乱起八糟的
 * 图标：就是我的头像

（最近在把博客从hexo转到typecho，可能到月底博客才能更新）

**Comment by 0x0cqq** [comment]
> @memset0
> 蒟蒻请求加友链
> 
>  * 名称：memset0的博客
>  * 地址：https://memset0.scris.top
>  * 简介：写点什么乱起八糟的
>  * 图标：就是我的头像
> 
> （最近在把博客从hexo转到typecho，可能到月底博客才能更新）

已加！谢谢神犇！

**Comment by memset0** [comment]
> @ChenQiqian
> > @memset0
> > 蒟蒻请求加友链
> > 
> >  * 名称：memset0的博客
> >  * 地址：https://memset0.scris.top
> >  * 简介：写点什么乱起八糟的
> >  * 图标：就是我的头像
> > 
> > （最近在把博客从hexo转到typecho，可能到月底博客才能更新）
> 
> 已加！谢谢神犇！

谢谢jvlao

**Comment by Cznorth** [comment]
ch.lol5.cn 互加友链丫
