### ISSUE TITLE
输入输出优化模板 | Chen's Blog

### ISSUE THREAD

**Issue by 0x0cqq** [ChenQiqian/comments#31]
http://blog.chenqiqian.com/20180223-IO-optimize/ 

 Stay simple. Stay naïve. 恭喜你！发现了一个蒟蒻的Blog。 某高中开始学OI的蒟蒻。现高一。 不定期更新。 (≧▽≦)/

**Comment by memset0** [comment]
洛谷观光团前来mod大佬

**Comment by 0x0cqq** [comment]
> @memset0
> 洛谷观光团前来mod大佬

%您！
