### ISSUE TITLE
冬令营旅游记 | Chen's Blog

### ISSUE THREAD

**Issue by 0x0cqq** [ChenQiqian/comments#6]
http://blog.chenqiqian.com/20180125-bjwc2018-trip/ 

 恭喜你！发现了一个蒟蒻的Blog。 某高中开始学OI的蒟蒻。 现高一。 不定期更新，主要看心情。 (≧▽≦)/

**Comment by memset0** [comment]
加油！！！

**Comment by memset0** [comment]
加油！！！

**Comment by 0x0cqq** [comment]
> @memset0
> 加油！！！

谢谢啦
